Export decision (#1921)
* Update "Hydraulic  Structures" to "Hydraulic Structures"

* Prevent AttributeError ('NoneType' object has no attribute 'data') when importing
empty or partial HDF5 files. If COORDINATES is absent/empty, calculate_cellsize()
now returns 0, to allow callers to fail gracefully.

* Update to honor user's explicit export decisions (Export + turn ON, Export ONLY, Cancel) when a non-prechecked component is checked during export.

* Update to honor user's explicit export decisions (Export + turn ON, Export ONLY, Cancel) when a non-prechecked component is checked during export.

* Update to honor user's explicit export decisions (Export + turn ON, Export ONLY, Cancel) when a non-prechecked component is checked during export.

* Update to ensure when exporting mud_sed, the dialog that appears (in the case of non-prechecked component) only has options has have been congiured.

* Update mud_sed asterisks logic so that asterisks appear even if only one table has data and the CONT is set to OFF (None)

* Update mud_sed part to ensure ONLY asterisks are used when it is set to None when both or one of mud/sed tables have data

* Modify h5py import structure to either fix the error:

Error while exporting RAINCELL data to hdf5 file!
Error:
   NameError: name 'h5py' is not defined
In file:
   C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\Master-MultD/python/plugins\flo2d\flo2d_ie\flo2dgeopackage.py
In function:
   export_raincell_hdf5
On line 8691:
^^^^

or raise a user friendly error message

* Add h5py import to either fix the error:

Error while exporting RAINCELL data to hdf5 file!
Error:
   NameError: name 'h5py' is not defined
In file:
   C:\Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\Master-MultD/python/plugins\flo2d\flo2d_ie\flo2dgeopackage.py
In function:
   export_raincell_hdf5
On line 8691:
^^^^

or raise a user friendly error message

* Update set_parser to show uniques error message for .DAT and .hdf5 formats when self.cell_size == 0

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update h5py import

* Update the logic for mud_sed export such that the components switch is OFF if the CONT switch is set to None, and export only happens when a specific physiscal process is set.

- Delete the asterisks part for mud_sed
- Delete the export action dialog for mud_sed

* Update the logic for mud_sed export such that the components switch is OFF if the CONT switch is set to None, and export only happens when a specific physiscal process is set.

- Delete the asterisks part for mud_sed
- Delete the export action dialog for mud_sed

* Convert the helper "handle_components" into a for loop for components export

* Convert the helper "handle_components" into a for loop for components export

* Update components export logic

* Revert to:

try:
    import h5py
except ImportError:
    pass

* Add export_action dialog

* Update to read export_action dialog from user-communication.py

* Add log_info and error_bar when import fails for hdf5

* flo2dgeopackage.py:

Update h5py import

Add error message and log to set_parser when h5py is missing, and return False  for the main ParseHDF5 workflow

Add error message and log to set_parser when h5py is missing, and return False specifically for export_raincell_hdf5

Add error message and log to set_parser when h5py is missing, and return False specifically for export_raincellraw_hdf5

* Update h5py import

* Add error messages and logs when hdf5 export fails

* Update h5py import

* Add more info to the log when set_parser is not ok

* Add log_info for set_parser error

* Update to use the user communication messages

* Update export dialog box to use the user communication dialog box

* Drop ask_component_export_action helper

* Update export dialog box to use the user communication dialog box

---------

Co-authored-by: Robson Pachaly <39889306+rpachaly@users.noreply.github.com>